# Dependencies
plugins:
  - jekyll-sitemap
  - jekyll-paginate

permalink: pretty
url: "https://github.com/ParkWonBin" 
baseurl: "htpps://wbpark.app" 

title: wbpark Dev Blog
email: pwb1128@gmail.com
description: the penguin
twitter_username: 
github_username:  ParkWonBin

# Pagination
paginate:            5
paginate_path:       '/page-:num/'


author:
  name:              'wbpark'

  # This photo will be used in the about section
  photo:             
  photo2x:           

markdown: kramdown
kramdown:
  input: GFM

compress_html:
  comments:          ["<!-- ", " -->"]
  clippings:         all
  endings:           all
  ignore:
    envs:            [local]

sass:
  style:             compressed
# Build settings
theme: minima
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - README_jekyll.md
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
