title: wbpark Dev Blog
author: 
  name: wbpark
  email: pwb1128@gmail.com

description: >- # this means to ignore newlines until "baseurl:"
  test123213

permalink: pretty
url: "https://github.com/ParkWonBin" 
# baseurl: "htpps://wbpark.app" 
# baseurl 입력하면 src의 시작 주소가 바뀐다.

github_username: ParkWonBin
twitter_username: 

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Pagination
paginate: 5
paginate_path: "/page:num/"

markdown: kramdown
kramdown:
  input: GFM

compress_html:
  comments:          ["<!-- ", " -->"]
  clippings:         all
  endings:           all
  ignore:
    envs:            [local]

sass:
  style:             compressed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/