title: wbpark Dev Blog
author: wbpark
email: pwb1128@gmail.com

description: >- # this means to ignore newlines until "baseurl:"
  기술블로그 제작중..

permalink: pretty
url: "https://github.com/ParkWonBin" 
# baseurl: "htpps://wbpark.app" 
# baseurl 입력하면 src의 시작 주소가 바뀐다.

github_username: ParkWonBin
tistory_username: phy64ev1
linkedin_username: wbpark14
instagram_username: wbpark14
facebook_username: wbpark14
pinterest_username: wbpark14
naverblog_username: wbpark14
youtube_username: AIPenguinStudio

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Pagination
paginate: 5
paginate_path: "/page:num/"

markdown: kramdown
kramdown:
  input: GFM

compress_html:
  comments:          ["<!-- ", " -->"]
  clippings:         all
  endings:           all
  ignore:
    envs:            [local]

sass:
  style:             compressed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/